requires 'Clone', '>=0.45';
requires 'DBIx::Class', '>=0.082';
requires 'DateTime';
requires 'DateTime::Format::Pg';
requires 'GraphQL::Plugin::Convert::DBIC';
requires 'Mojo::Pg', '>=4.19';
requires 'Mojolicious', '>=8.58';
requires 'Mojolicious::Plugin::GraphQL';
