on build => sub {
    requires 'Clone', '>=0.45';
    requires 'DBIx::Class', '>=0.082';
    requires 'DateTime';
    requires 'DateTime::Format::Pg';
    requires 'Mojo::Pg', '>=4.19';
    requires 'Mojolicious', '>=8.58';
};

on develop => sub {
    requires 'DBIx::Class::Schema::Loader';
    requires 'Config::General';
    requires 'DBD::Pg';
};