name: CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

  workflow_dispatch:

jobs:
  check-backend:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name:  Install tidyall
        run: sudo apt-get install -y perltidy libcode-tidyall-perl

      - name: Check coding style
        run: tidyall --check-only -a

      - name: Up backend with database
        run: docker-compose up -d db be

      - name: Run tests in backend
        run: docker-compose exec -T be prove -vl
  check-frontend:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Check coding style
        uses: creyD/prettier_action@v3.1
        with:
          prettier_options: --check **/app/**/*.{ts,html}
          only_changed: True
