name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  check-backend:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Check coding style
        run: |
          sudo apt-get install -y perltidy libcode-tidyall-perl
          tidyall --check-only --conf-file ./be-mojo/.tidyallrc -a

      - name: Up backend with database
        run: docker-compose up -d db be

      - name: Run tests in backend
        run: docker-compose exec -T be prove -vl
